@Backend_HostAddress = http://localhost:5275

GET {{Backend_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{Backend_HostAddress}}/api/job/location
Content-Type: application/json

{
  "latitude": 51.505,
  "longitude": 59.50,
  "searchdistance": 10
}

###
POST {{Backend_HostAddress}}/api/interview/get
Content-Type: application/json

{
  "Id": 1
}

###
GET {{Backend_HostAddress}}/api/interview/get

###

POST {{Backend_HostAddress}}/api/application/get
Content-Type: application/json

{
  "Id": 2
}

###
GET {{Backend_HostAddress}}/api/job/description/3

###
GET {{Backend_HostAddress}}/api/github/languages/Harsh-Patel-22/JSeeker


###
GET {{Backend_HostAddress}}/api/github/languages/


###
GET {{Backend_HostAddress}}/api/github/repositories/Harsh-Patel-22


###
GET {{Backend_HostAddress}}/api/github/repositories/Harsh-Patel-22/JSeeker


###
GET {{Backend_HostAddress}}/api/github/topics/Harsh-Patel-22/JSeeker


###
GET {{Backend_HostAddress}}/api/github/tags/Harsh-Patel-22/JSeeker


###
GET {{Backend_HostAddress}}/api/github/readme/Harsh-Patel-22/Tic-Tac-Toe_Game


###
POST {{Backend_HostAddress}}//api/auth/register
Content-Type: application/json

{
  "username": "Agent Dual Shards",
  "password": "Agent!!",
  "email": "hp22022005@gmail.com"
}

###
POST {{Backend_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "username": "Agent Dual Shards",
  "password": "Agent!!"
}



