@Backend_HostAddress = http://localhost:5275

GET {{Backend_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{Backend_HostAddress}}/api/joblocation
Content-Type: application/json

{
  "latitude": 51.505,
  "longitude": 59.50,
  "searchdistance": 10
}
